name: PR Validation

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run Lint
      - name: Run Linter
        run: npm run lint

      # 5. Run Tests with Coverage
      - name: Run Tests
        run: npm run test -- --coverage --watch=false

      # 6. Enforce Coverage threshold
      # - name: Check coverage
      #   run: |
      #     THRESHOLD=70
      #     COVERAGE=$(npx jest --coverage --coverageReporters=text-summary | grep 'All files' | awk '{print $4}' | sed 's/%//')
      #     echo "Coverage is $COVERAGE%"
      #     if [ "$COVERAGE" -lt "$THRESHOLD" ]; then
      #       echo "❌ Coverage below threshold ($THRESHOLD%)"
      #       exit 1
      #     fi
